# LiteLLM Configuration for Testing
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-35-turbo
      api_key: fake-key
      api_base: https://fake-base.openai.azure.com
      api_version: 2023-07-01-preview
      mock_response: "This is a mock response for testing."

litellm_settings:
  telemetry: false
  set_verbose: true
  json_logs: true
  drop_params: true
  num_retries: 3
  request_timeout: 15
  callbacks: ["arize_callback.arize_callback_instance"]
